### ISSUE TITLE
Spawning thread

### ISSUE THREAD

**Issue by dkundel** [dkundel/node-env-run#1]
It should probably rather spin up a new node process in favor of requiring the file. This way passing arguments like `-r` become more straight-forward.

**Comment by xzyfer** [comment]
💯  ideally this would work like

```js
  "scripts": {
    "dothing": "nodenv node-bin-that-expect-env arg1 arg2"
  }
```

**Comment by dkundel** [comment]
I finally got around solving this in `v3.0.0`. It's a slightly different syntax though. Check out the README for more info on it. Let me know if you have any questions.
