### ISSUE TITLE
Stop the main process

### ISSUE THREAD

**Issue by dannegm** [dkundel/node-env-run#2]
This is under maintenance? 9 months ago since the last update.

--

When I run the script with `nodenv .`, this run but, at the end to the script it's not live, they die.

**Comment by dkundel** [comment]
Hey @dannegm! 

I'm happy to do changes but I haven't had time to work on this "full-time". 

Can you explain a bit more what the problem is? This should really just be functioning as a wrapper. Do you have a minimal repro?

Cheers,
Dominik

**Comment by dkundel** [comment]
Hey @dannegm 

Check out version 3.0.0 that I just released and let me know if this fixed your issue. I'll close this issue in the mean time.

Cheers,
Dominik

**Comment by dannegm** [comment]
Thanks, I am going testing :)
