### ISSUE TITLE
Running on paths containing `` [space] throws an error 

### ISSUE THREAD

**Issue by hefler** [dkundel/node-env-run#9]
I've run it on a volume `External\ SSD` when renaming to `ExternalSSD` everything works fine. Here's the stack trace:
```
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '/Volumes/External'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by dkundel** [comment]
Hi @hefler can you give me a bit more background on how you are running the command? is your current working directory there or are you passing it in as an argument?

Cheers,
Dominik

**Comment by hefler** [comment]
@dkundel I think I ran it on the current directory and through a `npm script`. But in all honesty, I don’t remember for sure, I’m having a short vacation and I currently don’t have access to any external driver so I can’t replicate the issue again. Once I’m back I can give more insights.

**Comment by hefler** [comment]
I pretty much followed the doc examples. Installed it as a dev dependency and ran `npm run dev`, where in my project root folder I have an `.env` file. Here is the full log file: [debug.log](https://github.com/dkundel/node-env-run/files/4929624/debug.log).

**Comment by dkundel** [comment]
Hey @hefler. Thanks for the debug file. I was able to track down what's going on. The problem happens when the `spawn` function is called to start the new process. Node.js doesn't actually escape the arguments when starting the child process. I'm looking into solutions how to best handle the escaping but it has to handle a couple of edge cases and Windows support which proves to be tricky.

**Comment by dkundel** [comment]
@hefler this should be part of the new major version 4.0.1 :)

**Comment by hefler** [comment]
Awesome! Thanks @dkundel 🤘
